project_id = "hkthxnrcgohwjvpgbxyg"

[functions.reset-user-password]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.update-cutoff-date]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.create-portal-user]
verify_jwt = false

[functions.record-portal-login]
verify_jwt = true

[functions.approve-portal-request]
verify_jwt = true

[functions.ensure-portal-user]
verify_jwt = true